#!/bin/sh

WAL_COLORS="$HOME/.cache/wal/colors"

# Safety check
[ ! -f "$WAL_COLORS" ] && echo "Pywal colors not found! Run wal first." && exit 1

# Read needed colors
background=$(sed -n '1p' "$WAL_COLORS")
foreground=$(sed -n '2p' "$WAL_COLORS")
color4=$(sed -n '7p' "$WAL_COLORS")   # color4 for highlight

highlight_color="${color4#\#}"
selected_bg="${background#\#}"

# Launch choose with InconsolataGo Mono and pywal colors
choose -f "InconsolataGo Nerd Font Mono" -s 30 -c "$highlight_color" -b "$selected_bg" "$@" -n 10
